image: docker:git

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/blackestdawn/$CI_PROJECT_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - base image
  - S1 extension

base:
  stage: base image
  only:
    - tags
  script:
    - docker build -f Dockerfile-base -t $CONTAINER_IMAGE:base-$CI_COMMIT_TAG .
    - docker push $CONTAINER_IMAGE:base-$CI_COMMIT_TAG

packer:
  stage: S1 extension
  only:
    - tags
  script:
    - sed -i -e "s/\[\[TAG\]\]/$CI_COMMIT_TAG/g" Dockerfile-packer
    - docker build -f Dockerfile-packer -t $CONTAINER_IMAGE:packer-$CI_COMMIT_TAG .
    - docker push $CONTAINER_IMAGE:packer-$CI_COMMIT_TAG

isomaker:
  stage: S1 extension
  only:
    - tags
  script:
    - sed -i -e "s/\[\[TAG\]\]/$CI_COMMIT_TAG/g" Dockerfile-isomaker
    - docker build -f Dockerfile-isomaker -t $CONTAINER_IMAGE:isomaker-$CI_COMMIT_TAG .
    - docker push $CONTAINER_IMAGE:isomaker-$CI_COMMIT_TAG