# Dockerfile to expand on Ansible base docker image
#
# Version  0.1
#

# Base image
FROM registry.gitlab.com/blackestdawn/ansible-containers:base-[[TAG]]

# Labels and other metadata
LABEL maintainer="Alexander <blacke4dawn@gmail.com>"
ENV PACKER_VERSION=1.4.2
ENV VSPHERE_ISO_VERSION=2.3
ENV DEBIAN_FRONTEND=noninteractive

# All additional layers
RUN echo "===> Installing Packer and addons..." && \
  apt-get update && \
  apt-get install -y unzip && \
  wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && \
  wget https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v${VSPHERE_ISO_VERSION}/packer-builder-vsphere-iso.linux && \
  unzip packer_${PACKER_VERSION}_linux_amd64.zip && \
  install -m 0755 -t /usr/local/bin/ packer packer-builder-vsphere-iso.linux

RUN echo "===> Cleaning up..." && \
  rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/ansible.list packer_${PACKER_VERSION}_linux_amd64.zip && \
  apt-get clean -y
  
# default command: display Ansible version
CMD [ "ansible-playbook", "--version" ]
